config/routes.rb
Rails.application.routes.draw do
  resources :posts do             # ex: /post/:id/comments/edit/:id ...
    resources :comments
  end

  resources :comments do          # ex: /comment/:id/comments/edit/:id ...
    resources :comments
  end
  
  get 'history', to: 'comments#history' # comments controller history action

  devise_for :users
  root 'posts#index'
  get 'about', to: 'pages#about'

  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  before_create :set_comment_number

  # for action Text from Rails
  has_rich_text :body

  # for polymorphic Comments                                # polymorphic means connect a model to multiple other models: belongs to user,post,comment models
  belongs_to :commentable, polymorphic: true                # a comment belongs to a POST or a COMMENT
  has_many :comments, as: :commentable, dependent: :destroy # a comment can have many other comments

  private
  def set_comment_number  # == number of posts user created
    self.comment_number = user.comment_created
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  # for polymorphic Comments
  has_many :comments, as: :commentable, dependent: :destroy

  # for active Storage
  has_one_attached :thumbnail
  has_one_attached :banner
  
  # for action Text from Rails
  has_rich_text :body      

  validates :title, length: { minimum: 5 }
  validates :body, length: { minimum: 25 }

  # for pagination
  self.per_page = 10

  # for friendly_id
  extend FriendlyId
  friendly_id :title, use: :slugged

  def optimized_image(image, x, y)
    image.variant(resize_to_fill: [x, y]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_one_attached :avatar

  validates :username, presence: true, uniqueness: {case_sensitive: false}
  validate :validate_username

  attr_writer :login

  def validate_username
    errors.add(:username, :invalid) if User.where(email: username).exists?
  end

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  # def username
  #   self.email.split('@')[0].capitalize
  # end

  def comment_created
    self.number_of_comments += 1
    self.save
    number_of_comments
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :is_admin!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        added_attributes = %i[username email password password_confirmation remember_me avatar]
        devise_parameter_sanitizer.permit(:sign_up, keys: added_attributes)
        devise_parameter_sanitizer.permit(:account_update, keys: added_attributes)
    end

    private
    def is_admin!
        redirect_to(root_path) if !current_user || !current_user.admin?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_commentable, only: [:create]       
    before_action :set_comment, except: [:create]

    def create
        @comment = @commentable.comments.build(comment_params)
        @comment.user = current_user
        @comment.reply = true if params[:comment_id]
        @comment.save
    end

    def edit
    end

    def update
        if @comment.edit_history == ''      # default   # body is what we name our action text, and each action text has a body field
            @comment.edit_history = "Original: " + @comment.body.body.to_plain_text + "\n"
        else
            @comment.edit_history += "Edit: " + params[:comment][:body] + "\n"
        end                                     # what we are typing in the text area

        @comment.update(comment_params)
    end

    def destroy
        @comment.destroy
    end

    def history
    end

    private
    def comment_params
        params.require(:comment).permit(:body)
    end

    def find_commentable
        if params[:comment_id]                                      # is a comment
            @commentable = Comment.find_by_id(params[:comment_id])
        elsif params[:post_id]                                      # is a post
            @commentable = Post.friendly.find(params[:post_id])
        end
    end

    def set_comment
        @comment = Comment.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]      # can only look at index and show if NOT LOG IN
  before_action :is_admin!, except: [:index, :show]               # can only look at index and show if NOT LOG IN

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: Post.per_page)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.views += 1
    @post.save
    @comments = @post.comments.order("created_at DESC")

    @num_comments = @post.comments.count
    @post.comments.each { |comment| @num_comments += comment.comments.count }
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :thumbnail, :banner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class="comment-container", id="comment-<%= comment.id %>">
    <div class="container">
        <%# all PREVIOUS replies of current comment %>
        <%= render 'comments/comments', comment: comment, local: Comment.new %>

        <%# current comment's NEW reply form %>
        <% unless comment.reply %>                  <!-- uncomment for infinite nested comments-->
            <div class="row">
                <div class="col-4">

                </div>
                <div class="col-8">
                    <div class="comment-form-nested">
                        <%= render 'comments/form', commentable: comment, local: Comment.new %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/comments/_comments.html.erb
<div class="row">
    <div class="col-3">
    
        <div class="row">
            <% if comment.user.avatar.attached? %>
                <%= image_tag(comment.user.avatar, class:'comment-avatar') %>
            <% else %>
                <%= image_tag("/default_profile.png", class:'comment-avatar') %>
            <% end %>
        </div>

        <div class="row">
            <div class="comment-timestamp" id="edit-history-text-<%= comment.id %>">
                <%= render 'comments/edit_history_text', comment: comment%>
            </div>
        </div>

    </div>

    <div class="col-9">
        <div class="row">

            <div class="col-8">
                <div class="comment-username"><%= comment.user.username %></div>
                <div class="comment-number">#<%= comment.comment_number %></div>
            </div>

            <% if current_user && (current_user == comment.user || current_user.admin)%>
                <div class="col-4 text-right" style="padding-right: 0;">
                    <div class="btn-group" role="group" aria-label="Edit and Delete Button Group" style="float: right">
                        <%= link_to "Edit", edit_comment_path(comment), class: 'btn btn-warning', remote: true %>
                        <%= link_to "Delete", comment, class:'btn btn-danger', method: :delete, remote: true %>
                    </div>
                </div>
            <% end %>

        </div>

        <hr class="md-4">
        
        <div class="comment-body" id="comment-body-<%= comment.id %>">
            <%= comment.body %>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-3">
    </div>

    <div class="col-9">
        <div class="inner-comment-container" id="reply-<%= comment.id %>">
            <% comment.comments.each do |comment| %>
                <%= render comment %>
            <% end %>
        </div>
    </div>

</div>

<!-- Modal for edit history -->
<div class="modal fade" id="edit_history" tabindex="-1" role="dialog" aria-labelledby="Comment Edit History" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="edit_history_title">Edit History</h5>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body" id="edit-history-body">
                <%= render 'comments/edit_history', comment: comment %>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

app/views/comments/_edit_history.html.erb
<%= comment.edit_history.gsub(/\n/, '<br/><hr/>').html_safe %>
<%# gsub: search for(plain text that we saved) "\n" and replace it with a line break and a horizontal line %>

app/views/comments/_edit_history_text.html.erb
<%= time_ago_in_words(comment.created_at) %> ago
<br>
<% edit_history = comment.edit_history == "" ? "" : "Last edited " + time_ago_in_words(comment.updated_at) + " ago" %>
<%= link_to(edit_history, 'javascript:;', data: {toggle: "modal", target: "#edit_history"}) %>

app/views/comments/_form.html.erb
<% if current_user %>
    <%# REPLY FORM %>
    <div class="row">
        <div class="comment-form">
            <%= form_with model: [commentable, local] do |f| %>     <%# The form action is automatically filled with an appropriate values for @post and @comment %>
                <div class="form-group">                            <%# params[:post][:post_attributes]   ||    params[:comment][:comment_attribute] %>
                    <%= f.rich_text_area :body, placeholder: "Say something...", class: "reply-form-#{commentable.id}", id: f.object.object_id, method: :patch %>
                    <%= f.submit "Post", class: "btn btn-dark float-right" %>
                </div>
            <% end %>
        </div>
    </div>

    <script>
        $(document).on("turbolinks:load", function() {                          // listen for drag and drop file into rich_text_area
            $(".trix-button-group--file-tools").remove();                       // remove the attached file
            document.addEventListener("trix-file-accept", function(event) {     // preventDefault behavior
                event.preventDefault();
            });
        });
    </script>
<% else %>
    <div class="row">
        <div class="col-2"></div>
        
        <div class="col-8">
            <h2 class="comment-login-prompt"><%= link_to "Login", new_user_session_path %> to comment</h2>
        </div>

        <div class="col-2"></div>
    </div>
<% end %>

app/views/comments/create.js.erb
if ("<%= @comment.reply %>" === 'true') {
    var comment_pane;

    if ("<%= @commentable.comments.count %>" === "0") {
        comment_pane = "#reply-container-<%=@commentable.id %>";
    } else {
        comment_pane = "#reply-<%=@comment.commentable_id %>";
    }

    $(comment_pane).append("<%= j render @comment %>");
    $(".reply-form-<%= @commentable.id %>").value = '';
} else {
    $("#comment-pane").prepend("<%= j render @comment %>");
    $(".reply-form-<%= @commentable.id %>").value = '';
}

$('.trix-button-group--file-tools').remove();

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();

app/views/comments/edit.js.erb
$("#comment-body-<%= @comment.id %>").html("<%= j render 'comments/form', commentable: @comment.commentable, local: @comment %>");
$(".trix-button-group--file-tools").remove();

app/views/comments/update.js.erb
$("#comment-body-<%= @comment.id %>").html("<%= raw @comment.body.body.to_html() %>");
$("#edit-history-body").html("<%= j render 'comments/edit_history', comment: @comment %>");
$("#edit-history-text-<%= @comment.id %>").html("<%= j render 'comments/edit_history_text', comment: @comment %>");

app/views/layouts/_alerts_and_notices.html.erb
<% if notice || alert %>
  <div class="alert alert-warning" role="alert">
    <%= notice %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">BLOG</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<%= root_path %>">Home</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="<%= about_path %>">About</a>
          </li>
      </ul>
      <ul class="navbar-nav ml-auto">
          <% if current_user %>
              <li class="nav-item dropdown dropdown-right">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      <%= current_user.username %>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                      <li>
                          <% if current_user.admin %>
                              <a class="dropdown-item" href="<%= new_post_path %>">New Post</a>
                          <% end %>
                      </li>
                      <li><a class="dropdown-item" href="<%= edit_user_registration_path %>">Account Settings</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><%= link_to "Logout", destroy_user_session_path, class:'dropdown-item', method: :delete %></li>
                  </ul>
              </li>
          <% else %>
              <li class="nav-item">
                  <%= link_to "Signup", new_user_registration_path, class:'nav-link' %>
              </li>
              <li class="nav-item">
                  <%= link_to "Signin", new_user_session_path, class:'nav-link' %>
              </li>
          <% end %>
      </ul>
    </div>
  </div>
</nav> 

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/alerts_and_notices" %>
    <%= yield %>
  </body>
</html>

app/views/pages/_social_media_links.html.erb
<button type="button" onclick="window.location.href = 'https://github.com/haolam05';"                               class="btn btn-secondary">GitHub</button>
<button type="button" onclick="window.location.href = 'https://www.instagram.com/lth.______/';"                     class="btn btn-secondary">Instagram</button>
<button type="button" onclick="window.location.href = 'https://www.facebook.com/profile.php?id=100006248883342';"   class="btn btn-secondary">YouTube</button>

app/views/pages/about.html.erb
<div class="container" style="background-color: #e9ecef; margin-top: 5px;">
    <div class="jumbotron">
        <h1 class="display-4">About Me</h1>
    
        <div class="row">
            <p style="text-align: justify">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nec ultrices dui sapien eget mi proin sed libero. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Turpis egestas integer eget aliquet nibh praesent tristique magna. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. Dictum sit amet justo donec enim diam. Sit amet cursus sit amet dictum sit amet justo. Euismod quis viverra nibh cras pulvinar. Ultricies integer quis auctor elit sed vulputate mi sit. Dui vivamus arcu felis bibendum ut. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Turpis tincidunt id aliquet risus feugiat in ante metus dictum. Cursus turpis massa tincidunt dui ut ornare.
                <br><br>
                Viverra mauris in aliquam sem fringilla. Nulla malesuada pellentesque elit eget. Arcu non odio euismod lacinia at quis risus. Vel pharetra vel turpis nunc eget lorem dolor sed viverra. Lorem ipsum dolor sit amet consectetur. Senectus et netus et malesuada fames ac turpis. Dictumst quisque sagittis purus sit amet volutpat. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Sit amet commodo nulla facilisi. Facilisi nullam vehicula ipsum a. Blandit cursus risus at ultrices mi. Semper quis lectus nulla at volutpat diam ut venenatis tellus. In fermentum posuere urna nec tincidunt praesent semper feugiat.
            </p>
            <hr class="my-4"/>
        </div>
        <div class="btn-group" role="group" aria-label="Basic example">
            <%= render "pages/social_media_links" %>
        </div>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
  <div class="form-inputs">
    <%= f.label :title, class: "form-control" %>
    <%= f.text_field :title, class: "form-control string" %>

    <%= f.label :thumbnail, class: "form-control" %>
    <%= f.file_field :thumbnail %>

    <%= f.label :banner, class: "form-control" %>
    <%= f.file_field :banner %>

    <%= f.label :body, class: "form-control" %>
    <%= f.rich_text_area :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Views:</strong>
    <%= post.views %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">

      <%# from pagination %>
      <div class="digg_pagination">
          <%# <div class="page_info"><%= page_entries_info @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer</div> %> 
          <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </div>
      <%# from pagination %>



    <% @posts.each do |post| %>
      <div class="row">
          <div class="card mb-3">
              <img class="card-img-top" src="<%= url_for post.optimized_image(post.thumbnail, 586, 180) %>" alt="Blog Post Image Card" />
              
              <div class="card-body">
                  <h5 class="card-title"><%= link_to post.title, post %></h5>
                  <p class="card-text"><%= post.body.to_plain_text.truncate_words(50) %></p>  <%# workaround for action text => to_plain_text() => then truncate %>
                  <p class="card-text">
                      <small class="text-muted">
                            <%= post.updated_at.strftime("%A, %B %e, %Y") %> by
                            <%= post.user.username %> | <%= pluralize(post.views, "View") %> | 
                          
                            <% @num_comments = post.comments.count %>
                            <% post.comments.each do |comment| %>
                                <% @num_comments += comment.comments.count %>
                            <% end %>
                            
                            <%= pluralize(@num_comments, "Comment") %> |

                            <% if current_user && (post.user || current_user.admin) %>
                                <%= link_to "Delete", post, method: :delete, data: { confirm: "Are you sure?" } %>
                            <% end %>
                      </small>
                  </p>
              </div>
              
          </div>
      </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<div style="width:100%; height: 300px; overflow-y:hidden">
  <%= image_tag(@post.banner, style:'width:100%') %>
</div>

<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="jumbotron" style="width:100%">

      <h1 class="display-4"><%= link_to @post.title, root_path %></h1>
      
      <p class="lead"><%= @post.updated_at.strftime("%A, %B %e, %Y") %> by <%= @post.user.username %> | <%= pluralize(@post.views, "View") %></p>

      <hr class="my-4">

      <div class="post_body"><%= @post.body %></div>

    </div>
  </div>
</div>

<div class="container">
  <%= render "comments/form", commentable: @post, local: Comment.new %>             <!-- post's reply form -->

  <div id="comment-pane">
    <% @comments.each do |comment| %>   
      <%= render comment %>                                                         <!-- "comments/comment" partial -->
    <% end %>
  </div>
</div>